p8105_hw6
================
Maliha Safdar
2025-11-29

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.1
    ## ✔ ggplot2   4.0.0     ✔ tibble    3.3.0
    ## ✔ lubridate 1.9.4     ✔ tidyr     1.3.1
    ## ✔ purrr     1.1.0     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(modelr)
library(broom)
```

    ## 
    ## Attaching package: 'broom'
    ## 
    ## The following object is masked from 'package:modelr':
    ## 
    ##     bootstrap

``` r
library(p8105.datasets)
weather_df = p8105.datasets::weather_df
```

### Problem 1

`First, we will go ahead and import the data.`

``` r
### importing the dataset

homicide_daf = read.csv("homicide-data.csv")
```

`Next, create city_state and solved variable. The solved variable will be binary so any case that is not closed with arrest will be 0. The victim_age will be converted to numeric using mutate function. We will use the filter function to ensure that Dallas, Phoenix, Kansas City and Tulsa are removed from city_state variable as well as only including White and Black race in victim_race.`

``` r
### creating city_state variable, making binary variable for disposition, omitting Dallas, Phoenix, Kansas City and Tulsa,selecting white+black for victime_race and contverting victime_age to numeric.

homicide_df = homicide_daf |>
  mutate(
    city_state = str_c(city,state, sep = ","),
    solved = if_else(disposition == "Closed by arrest", 1, 0),
    victim_age = as.numeric(victim_age)
    ) |>
  filter(
    !city_state %in% c("Dallas,TX", "Phoenix,AZ", "Kansas City,MO","Tulsa,AL"),
    victim_race %in% c ("White", "Black")
  )
```

    ## Warning: There was 1 warning in `mutate()`.
    ## ℹ In argument: `victim_age = as.numeric(victim_age)`.
    ## Caused by warning:
    ## ! NAs introduced by coercion

`Now we will fit a logistic regression  with solved and unsolved homicide cases as outcome and victime age, sex and race as predictors. For this model we will use Baltimore, MD from the city_state variable.`

``` r
#filter for Baltimore, MD and create a variable for it.

baltimore <- homicide_df |>
  filter(city_state%in% c("Baltimore,MD"))

# create the logistical model

log_model <- glm(solved ~ victim_age + victim_sex + victim_race, data = baltimore, family = binomial())

log_model |>
  tidy(conf.int = TRUE) |>
  filter(term == "victim_sexMale") |>
  mutate(
    OR = exp(estimate),
    CI_low = exp(conf.low),
    CI_high = exp(conf.high)
  ) |>
  select(OR, CI_low, CI_high) |>
  knitr::kable(digits = 3)
```

|    OR | CI_low | CI_high |
|------:|-------:|--------:|
| 0.426 |  0.324 |   0.558 |

`When comparing males versus females, we see that the odds ratio for solving homicide cases is 0.426 with a confidence interval between 0.324 and 0.558.`

`Next we will perform logistic regression for every city in the dataset, and extract the odds ratio and CIs. We will compare males vs female victims.`

``` r
cities <- homicide_df |>
  group_by(city_state) |>
  nest() |>
  mutate(
    model = map(data, ~ glm(solved ~ victim_age + victim_sex + victim_race, data= .x, family = binomial ())),
    results = map(model, ~ broom::tidy(.x, conf.int = TRUE))
  ) |>
  unnest(results) |>
  filter(term == "victim_sexMale") |>
  mutate(
    OR = exp(estimate),
    CI_low = exp(conf.low),
    CI_high = exp(conf.high)
  ) |>
  select(city_state, OR, CI_low, CI_high)

cities |>
  knitr::kable(digits = 3)
```

| city_state        |    OR | CI_low | CI_high |
|:------------------|------:|-------:|--------:|
| Albuquerque,NM    | 1.767 |  0.825 |   3.762 |
| Atlanta,GA        | 1.000 |  0.680 |   1.458 |
| Baltimore,MD      | 0.426 |  0.324 |   0.558 |
| Baton Rouge,LA    | 0.381 |  0.204 |   0.684 |
| Birmingham,AL     | 0.870 |  0.571 |   1.314 |
| Boston,MA         | 0.674 |  0.353 |   1.277 |
| Buffalo,NY        | 0.521 |  0.288 |   0.936 |
| Charlotte,NC      | 0.884 |  0.551 |   1.391 |
| Chicago,IL        | 0.410 |  0.336 |   0.501 |
| Cincinnati,OH     | 0.400 |  0.231 |   0.667 |
| Columbus,OH       | 0.532 |  0.377 |   0.748 |
| Denver,CO         | 0.479 |  0.233 |   0.962 |
| Detroit,MI        | 0.582 |  0.462 |   0.734 |
| Durham,NC         | 0.812 |  0.382 |   1.658 |
| Fort Worth,TX     | 0.669 |  0.394 |   1.121 |
| Fresno,CA         | 1.335 |  0.567 |   3.048 |
| Houston,TX        | 0.711 |  0.557 |   0.906 |
| Indianapolis,IN   | 0.919 |  0.678 |   1.241 |
| Jacksonville,FL   | 0.720 |  0.536 |   0.965 |
| Las Vegas,NV      | 0.837 |  0.606 |   1.151 |
| Long Beach,CA     | 0.410 |  0.143 |   1.024 |
| Los Angeles,CA    | 0.662 |  0.457 |   0.954 |
| Louisville,KY     | 0.491 |  0.301 |   0.784 |
| Memphis,TN        | 0.723 |  0.526 |   0.984 |
| Miami,FL          | 0.515 |  0.304 |   0.873 |
| Milwaukee,wI      | 0.727 |  0.495 |   1.054 |
| Minneapolis,MN    | 0.947 |  0.476 |   1.881 |
| Nashville,TN      | 1.034 |  0.681 |   1.556 |
| New Orleans,LA    | 0.585 |  0.422 |   0.812 |
| New York,NY       | 0.262 |  0.133 |   0.485 |
| Oakland,CA        | 0.563 |  0.364 |   0.867 |
| Oklahoma City,OK  | 0.974 |  0.623 |   1.520 |
| Omaha,NE          | 0.382 |  0.199 |   0.711 |
| Philadelphia,PA   | 0.496 |  0.376 |   0.650 |
| Pittsburgh,PA     | 0.431 |  0.263 |   0.696 |
| Richmond,VA       | 1.006 |  0.483 |   1.994 |
| San Antonio,TX    | 0.705 |  0.393 |   1.238 |
| Sacramento,CA     | 0.669 |  0.326 |   1.314 |
| Savannah,GA       | 0.867 |  0.419 |   1.780 |
| San Bernardino,CA | 0.500 |  0.166 |   1.462 |
| San Diego,CA      | 0.413 |  0.191 |   0.830 |
| San Francisco,CA  | 0.608 |  0.312 |   1.155 |
| St. Louis,MO      | 0.703 |  0.530 |   0.932 |
| Stockton,CA       | 1.352 |  0.626 |   2.994 |
| Tampa,FL          | 0.808 |  0.340 |   1.860 |
| Tulsa,OK          | 0.976 |  0.609 |   1.544 |
| Washington,DC     | 0.690 |  0.465 |   1.012 |

`Making a plot to show the estimated ORs and CI for each city.`

``` r
cities |>
  ggplot(aes(x = reorder(city_state, OR), y = OR)) +
  geom_point() +
  geom_errorbar(aes(ymin = CI_low, ymax = CI_high)) +
  labs(
    title = "Est Odds Ration for Solved Homicide Cases For Each City",
    x = "City, State",
    y = " Odds ratio (Male vs Female"
  ) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

![](p8105_hw6_ms7354_files/figure-gfm/unnamed-chunk-6-1.png)<!-- -->
